trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    # Loss should be minimized
    goal: MINIMIZE
    maxTrials: 20
    maxParallelTrials: 2
    params:
      - parameterName: num-skips
        minValue: 2
        maxValue: 32
        type: INTEGER
      - parameterName: skip-window
        minValue: 4
        maxValue: 64
        type: INTEGER
