apiVersion: v1
kind: Pod
metadata:
   name: debug
spec:
   containers:
       - name: debug
         image: debian:latest
         command: ["sleep", "100000"]
         volumeMounts:
             - name: tensorflow-fs
               mountPath: /var/tensorflow
   volumes:
       - name: tensorflow-fs
         persistentVolumeClaim:
             claimName: tensorflow-fs
