kind: PersistentVolume
apiVersion: v1
metadata:
  name: tensorflow-fs
  namespace: default
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    nfs:
        server: 0.0.0.0
        path: "/exports"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-fs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi